// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebUD5.Models;

[Table("transactions")]
[Index("TransactionCode", Name = "UQ__transact__DD5740BE32A3579B", IsUnique = true)]
public partial class Transaction
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("payment_id")]
    public int PaymentId { get; set; }

    [Required]
    [Column("transaction_code")]
    [StringLength(255)]
    public string TransactionCode { get; set; }

    [Column("amount", TypeName = "decimal(18, 2)")]
    public decimal Amount { get; set; }

    [Required]
    [Column("transaction_status")]
    [StringLength(50)]
    public string TransactionStatus { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("response_message")]
    public string ResponseMessage { get; set; }

    [ForeignKey("PaymentId")]
    [InverseProperty("Transactions")]
    public virtual Payment Payment { get; set; }
}