// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebUD5.Models;

[Table("users")]
[Index("Email", Name = "UQ__users__AB6E61647657ABC4", IsUnique = true)]
[Index("Username", Name = "UQ__users__F3DBC572EF5C5B9E", IsUnique = true)]
public partial class User
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("username")]
    [StringLength(255)]
    public string Username { get; set; }

    [Required]
    [Column("password_hash")]
    [StringLength(255)]
    public string PasswordHash { get; set; }

    [Required]
    [Column("full_name")]
    [StringLength(255)]
    public string FullName { get; set; }

    [Column("gender")]
    public int? Gender { get; set; }

    [Required]
    [Column("email")]
    [StringLength(255)]
    public string Email { get; set; }

    [Column("email_verified")]
    public bool EmailVerified { get; set; }

    [Column("verification_token")]
    [StringLength(255)]
    public string VerificationToken { get; set; }

    [Required]
    [Column("phone")]
    [StringLength(20)]
    public string Phone { get; set; }

    [Column("address")]
    [StringLength(500)]
    public string Address { get; set; }

    [Column("birthday")]
    public DateTime? Birthday { get; set; }

    [Column("img_profile")]
    [StringLength(100)]
    public string ImgProfile { get; set; }

    [Column("role")]
    [StringLength(50)]
    public string Role { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [Column("status")]
    public bool Status { get; set; }

    [Column("reset_token")]
    [StringLength(255)]
    public string ResetToken { get; set; }

    [Column("reset_token_expiry", TypeName = "datetime")]
    public DateTime? ResetTokenExpiry { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<OrderHistory> OrderHistories { get; set; } = new List<OrderHistory>();

    [InverseProperty("Shipper")]
    public virtual ICollection<Order> OrderShippers { get; set; } = new List<Order>();

    [InverseProperty("User")]
    public virtual ICollection<Order> OrderUsers { get; set; } = new List<Order>();

    [InverseProperty("User")]
    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    [InverseProperty("Seller")]
    public virtual ICollection<Product> Products { get; set; } = new List<Product>();

    [InverseProperty("User")]
    public virtual ICollection<RequestManagement> RequestManagements { get; set; } = new List<RequestManagement>();

    [InverseProperty("User")]
    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    [InverseProperty("User")]
    public virtual ICollection<UserVoucher> UserVouchers { get; set; } = new List<UserVoucher>();

    [InverseProperty("CreatedByNavigation")]
    public virtual ICollection<Voucher> Vouchers { get; set; } = new List<Voucher>();

    [InverseProperty("User")]
    public virtual ICollection<Wishlist> Wishlists { get; set; } = new List<Wishlist>();
}