// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebUD5.Models;

[Table("user_vouchers")]
public partial class UserVoucher
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("user_id")]
    public int UserId { get; set; }

    [Column("voucher_id")]
    public int VoucherId { get; set; }

    [Column("used")]
    public bool? Used { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("UserVouchers")]
    public virtual User User { get; set; }

    [ForeignKey("VoucherId")]
    [InverseProperty("UserVouchers")]
    public virtual Voucher Voucher { get; set; }
}