// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebUD5.Models;

[Table("vouchers")]
[Index("Code", Name = "UQ__vouchers__357D4CF920FF58A8", IsUnique = true)]
public partial class Voucher
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("code")]
    [StringLength(50)]
    public string Code { get; set; }

    [Column("discount_percentage", TypeName = "decimal(5, 2)")]
    public decimal DiscountPercentage { get; set; }

    [Column("max_discount", TypeName = "decimal(18, 2)")]
    public decimal? MaxDiscount { get; set; }

    [Column("expiry_date", TypeName = "datetime")]
    public DateTime ExpiryDate { get; set; }

    [Column("created_by")]
    public int CreatedBy { get; set; }

    [Column("role")]
    [StringLength(50)]
    public string Role { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("CreatedBy")]
    [InverseProperty("Vouchers")]
    public virtual User CreatedByNavigation { get; set; }

    [InverseProperty("Voucher")]
    public virtual ICollection<UserVoucher> UserVouchers { get; set; } = new List<UserVoucher>();

    [InverseProperty("Voucher")]
    public virtual ICollection<VoucherProduct> VoucherProducts { get; set; } = new List<VoucherProduct>();
}