// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebUD5.Models;

[Table("voucher_products")]
[Index("VoucherId", "ProductId", Name = "UQ__voucher___C4C6D87695ACD406", IsUnique = true)]
public partial class VoucherProduct
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("voucher_id")]
    public int VoucherId { get; set; }

    [Column("product_id")]
    public int ProductId { get; set; }

    [Column("created_at", TypeName = "datetime")]
    public DateTime? CreatedAt { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("VoucherProducts")]
    public virtual Product Product { get; set; }

    [ForeignKey("VoucherId")]
    [InverseProperty("VoucherProducts")]
    public virtual Voucher Voucher { get; set; }
}