// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebUD5.Models;

public partial class WebUD5DbContext : DbContext
{
    public WebUD5DbContext(DbContextOptions<WebUD5DbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderHistory> OrderHistories { get; set; }

    public virtual DbSet<OrderItem> OrderItems { get; set; }

    public virtual DbSet<Payment> Payments { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductImage> ProductImages { get; set; }

    public virtual DbSet<RequestManagement> RequestManagements { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    public virtual DbSet<User> Users { get; set; }

    public virtual DbSet<UserVoucher> UserVouchers { get; set; }

    public virtual DbSet<Voucher> Vouchers { get; set; }

    public virtual DbSet<VoucherProduct> VoucherProducts { get; set; }

    public virtual DbSet<Wishlist> Wishlists { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__categori__3213E83FF05CF3C0");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__orders__3213E83FC2B57BA1");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.DeliveryStatus).HasDefaultValue("Pending");
            entity.Property(e => e.Status).HasDefaultValue("pending");

            entity.HasOne(d => d.Shipper).WithMany(p => p.OrderShippers).HasConstraintName("FK__orders__shipper___59FA5E80");

            entity.HasOne(d => d.User).WithMany(p => p.OrderUsers).HasConstraintName("FK__orders__user_id__59063A47");
        });

        modelBuilder.Entity<OrderHistory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__order_hi__3213E83F90AFDBA8");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderHistories).HasConstraintName("FK__order_his__order__6383C8BA");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderHistories)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order_his__produ__6477ECF3");

            entity.HasOne(d => d.User).WithMany(p => p.OrderHistories)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order_his__user___628FA481");
        });

        modelBuilder.Entity<OrderItem>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__order_it__3213E83FEE9AF764");

            entity.HasOne(d => d.Order).WithMany(p => p.OrderItems).HasConstraintName("FK__order_ite__order__5CD6CB2B");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderItems)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__order_ite__produ__5DCAEF64");
        });

        modelBuilder.Entity<Payment>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__payments__3213E83FBC08E7AB");

            entity.Property(e => e.PaymentDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Status).HasDefaultValue("pending");

            entity.HasOne(d => d.Order).WithMany(p => p.Payments).HasConstraintName("FK__payments__order___05D8E0BE");

            entity.HasOne(d => d.User).WithMany(p => p.Payments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__payments__user_i__06CD04F7");
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__products__3213E83F1FA888A0");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Status).HasDefaultValue("pending");
            entity.Property(e => e.StockQuantity).HasDefaultValue(0);

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__products__catego__4E88ABD4");

            entity.HasOne(d => d.Seller).WithMany(p => p.Products).HasConstraintName("FK__products__seller__4D94879B");
        });

        modelBuilder.Entity<ProductImage>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__product___3213E83FEE24AD2E");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductImages).HasConstraintName("FK__product_i__produ__52593CB8");
        });

        modelBuilder.Entity<RequestManagement>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__request___3213E83FA0ABB029");

            entity.Property(e => e.RequestDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.Status).HasDefaultValue("pending");

            entity.HasOne(d => d.User).WithMany(p => p.RequestManagements).HasConstraintName("FK__request_m__user___440B1D61");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__reviews__3213E83FB76CC739");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Product).WithMany(p => p.Reviews)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__reviews__product__7F2BE32F");

            entity.HasOne(d => d.User).WithMany(p => p.Reviews).HasConstraintName("FK__reviews__user_id__7E37BEF6");
        });

        modelBuilder.Entity<Transaction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__transact__3213E83F81734686");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Payment).WithMany(p => p.Transactions).HasConstraintName("FK__transacti__payme__0C85DE4D");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__users__3213E83F235531A7");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.EmailVerified).HasDefaultValue(false);
            entity.Property(e => e.Role).HasDefaultValue("customer");
            entity.Property(e => e.Status).HasDefaultValue(true);
        });

        modelBuilder.Entity<UserVoucher>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__user_vou__3213E83F8593EEB9");

            entity.Property(e => e.Used).HasDefaultValue(false);

            entity.HasOne(d => d.User).WithMany(p => p.UserVouchers).HasConstraintName("FK__user_vouc__user___787EE5A0");

            entity.HasOne(d => d.Voucher).WithMany(p => p.UserVouchers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__user_vouc__vouch__797309D9");
        });

        modelBuilder.Entity<Voucher>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__vouchers__3213E83FB12DFDF6");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.CreatedByNavigation).WithMany(p => p.Vouchers).HasConstraintName("FK__vouchers__create__6EF57B66");
        });

        modelBuilder.Entity<VoucherProduct>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__voucher___3213E83F8F0289A0");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Product).WithMany(p => p.VoucherProducts).HasConstraintName("FK__voucher_p__produ__74AE54BC");

            entity.HasOne(d => d.Voucher).WithMany(p => p.VoucherProducts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__voucher_p__vouch__73BA3083");
        });

        modelBuilder.Entity<Wishlist>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__wishlist__3213E83F5244D0DB");

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Product).WithMany(p => p.Wishlists)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__wishlist__produc__693CA210");

            entity.HasOne(d => d.User).WithMany(p => p.Wishlists).HasConstraintName("FK__wishlist__user_i__68487DD7");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}